### PR TITLE
Log tags need to be shorter than 24 chars according to android docume…

### PR DESCRIPTION
**Pull request by delta2wye**
…ntation

http://developer.android.com/reference/android/util/Log.html#isLoggable(java.lang.String,%20int)

### CODE REVIEW

**Comment by WonderCsabo** [comment]
Thanks for this PR! We have the same problem in `TransactionalHandler` and `OrmLiteDaoHandler`? Can you fix those as well? And maybe you can extract this into a helper class as well for example `LogHelper`.

**Comment by delta2wye** [comment]
@WonderCsabo bump

**Comment by WonderCsabo** [comment]
Thanks! Can i ask you to:

- fix the header in the new class (the build is failed because of that)
- please reword your commit messages per the contributor guide in the wiki
- add an overload to the log helper method, which accepts a `GeneratedClassHolder` (so we can remove more code duplication)
- squash the last commits

**Comment by WonderCsabo** [comment]
@delta2wye can you update the PR?

**Pull request closed without merging**
