### PR TITLE
remove model parameter from @OrmLiteDao

### PR DESCRIPTION
**Pull request by dodgex**
according to the [wiki](https://github.com/excilys/androidannotations/wiki/Ormlite) this should have been gone already. ;)

### CODE REVIEW

**Comment by yDelouis** [comment]
Thanks.

**Comment by WonderCsabo** [comment]
@dodgex can you update the wiki?

**Comment by dodgex** [comment]
https://github.com/dodgex/androidannotations/wiki/Ormlite

i wonder if we want to deprecate `helper` and just use `value` instead (no need to write the attribute name in code).

**Comment by WonderCsabo** [comment]
I think it is a good idea. Actually we can just rename since 4.0 is a
breaking release already. @yDelouis WDYT?

**Comment by yDelouis** [comment]
I'm not sure we should rename it. It tells clearly what parameter is expected.
But if you think it's ok, go for it.

**Comment by WonderCsabo** [comment]
@yDelouis i think you are right.

**Comment by WonderCsabo** [comment]
@dodgex i merged your wiki changes, thanks.

**Pull request merged**
