### PR TITLE
Add new system services from API 23

### PR DESCRIPTION
**Pull request by WonderCsabo**
Related to #1797 .

### CODE REVIEW

**Comment by dodgex** [comment]
Have you checked if there are new services for API 24? As the API is final and a release should not be too far from now, we should add them too.

**Comment by WonderCsabo** [comment]
Nope, i did not. Usually i just loo like the GitHub mirror `android_frameworks_base` repo. I think we should add those only if API 24 is released.

**Comment by WonderCsabo** [comment]
BTW @dodgex, did you look at the code? Should i merge this? :)

**Comment by dodgex** [comment]
While I can understand that, I think in should be no harm to have them before. As you can already publish Apps for API24 to play store.

**Comment by WonderCsabo** [comment]
@dodgex i did not know that. I can add those if you point me to the relevant repository. :)

**Comment by dodgex** [comment]
[here](http://android-developers.blogspot.de/2016/06/android-n-apis-are-now-final.html) is the related Android Developers Blog.

i checked from docs and those are the ones i found added with API 24.
[SYSTEM_HEALTH_SERVICE](https://developer.android.com/reference/android/content/Context.html#SYSTEM_HEALTH_SERVICE)
[HARDWARE_PROPERTIES_SERVICE](https://developer.android.com/reference/android/content/Context.html#HARDWARE_PROPERTIES_SERVICE)


about the changes you already made: i think it looks okay.

**Comment by WonderCsabo** [comment]
@dodgex added the new services.

**Pull request merged**
