### PR TITLE
Update AndroidManifest.java

### PR DESCRIPTION
**Pull request by blackb00m**
Fix of an assignment of the parameter to itself instead of the class field.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
Nice catch! Thanks. This line was broken by https://github.com/excilys/androidannotations/commit/2ee251d00cd7d86814c1486844ca180af943aeb3#diff-d29654a60dfa65217895cded5ca1943eR50. This property is not used currently, but would cause troubles in the future.

BTW, can you ask you to reword the commit as to add a more descriptive commit message per the [contribution guidelines](https://github.com/excilys/androidannotations/wiki/HowToContributeCode#checklist-for-contributed-code)? Also, next time please use a [proper branch name](https://github.com/excilys/androidannotations/wiki/HowToContributeCode#general-steps)! (I know you just edited the file with the GitHub editor now.)

**Comment by blackb00m** [comment]
Yep, you're right) Visited your project repo for the first time, chose a random file just to see how the framework works, found the problem and fixed it)
I'm a bit lazy to fork a repo for fixing such a small issue, but promise to do this next time :)

**Comment by WonderCsabo** [comment]
Yeah, thanks for keeping to the [boy scout rule](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)! We welcome any contributions, from a typo fix to a big refactor.

No worries, and thanks! ;)

**Comment by WonderCsabo** [comment]
Can you rebase this branch onto develop?

**Comment by WonderCsabo** [comment]
Merged as of 314fbec9.

**Pull request closed without merging**
