### PR TITLE
Handle special case when injecting AppWidgetManager with @SystemService

### LINKED ISSUE #1377: @SystemService & android.appwidget.AppWidgetManager
Given I inject the AppWidgetManager service into a Fragment like this:

```
@SystemService
protected AppWidgetManager appWidgetManager;
```

Then the generated code looks like this:
```
appWidgetManager = ((AppWidgetManager) getActivity().getSystemService(Context.APPWIDGET_SERVICE));
```

However, this will result in NPE, because AppWidgetManager can not be retrieved like that.

Instead, the following code should be generated:
```
appWidgetManager = AppWidgetManager.getInstance(getActivity());
```

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #1377.

### CODE REVIEW

**Comment by dodgex** [comment]
Looks good. +1 for checking the sdk & current Plattform to decide how to inject. 

I think you verified the results, but is there a way to add a test?

**Comment by WonderCsabo** [comment]
Thanks for checking the PRs!

I wanted to add tests, but unfortunately there is no way to test this, because we do not have the API 21 classes at compile time. Actually we could just provide a dummy class, but we cannot add a new field to `Build.VERSION_CODES`.

**Comment by WonderCsabo** [comment]
Hmm, i just thought about the compile time test (because this should be done there), but maybe we could do it in the functional test with the help of Robolectric.

Actually it is a pain that we still depend on Android 4.x. I tend to create a solution to create a script which installs the Android dependency to the local maven repo, as lots of Android projects the (this is [needed](https://github.com/robolectric/robolectric/blob/master/scripts/install-dependencies.sh) for the compilation of Robolectric itself, for example).

**Comment by WonderCsabo** [comment]
@dodgex i added a commit which tests one case of injection (when only the old method is available). It would be nice to do it in compile time test, but we cannot do that currently.

**Comment by dodgex** [comment]
@WonderCsabo i assumed that it would be hard to get proper tests for that. lets hope no one breaks that accidently :D

**Comment by yDelouis** [comment]
I'm okay with the code but the Travis build has failed. Could you fix this ?

**Comment by WonderCsabo** [comment]
Thanks for checking!

The Travis failure is not related to this PR, this passed. For some reason, it fails while [unzipping](https://travis-ci.org/excilys/androidannotations/jobs/60349974#L4026) the Gradle distribution. I am seeing this problems lately. I try to investigate.

**Comment by WonderCsabo** [comment]
Maybe Travis is unstable [now](https://twitter.com/traviscistatus/status/592902357144498176). I also see other errors, like build freezing while downloading Maven deps.

**Comment by yDelouis** [comment]
OK. Feel free to merge this PR if it builds locally.

**Pull request merged**
