### PR TITLE
Added newline at eof checkstyle rule.

### PR DESCRIPTION
**Pull request by johncarl81**

### CODE REVIEW

**Comment by dodgex** [comment]
nice one :+1:

**Comment by johncarl81** [comment]
Not sure why Travis is unhappy.. any ideas?

**Comment by dodgex** [comment]
```
[ERROR] src/test/java/org/androidannotations/rest/spring/ClientWithWrongEnhancedMethod.java[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src/test/java/org/androidannotations/rest/spring/WrongConstructorInterceptor.java[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src/test/java/org/androidannotations/rest/spring/WrongConstructorResponseErrorHandler.java[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
```

**Comment by WonderCsabo** [comment]
Thanks for this PR! Can you correct the three files listed https://github.com/excilys/androidannotations/pull/1560#issuecomment-141632986 ?

**Pull request merged**
