### PR TITLE
1532 add option to remove final modifier from generated classes

### PR DESCRIPTION
**Pull request by dodgex**
see https://github.com/excilys/androidannotations/issues/1532

### CODE REVIEW

**Comment by dodgex** [comment]
Wiki: https://github.com/dodgex/androidannotations/wiki/CustomizeAnnotationProcessing#generatefinalclasses

**Comment by WonderCsabo** [comment]
@yDelouis are you OK with this?

**Comment by yDelouis** [comment]
Yes, it seems good !

**Comment by yDelouis** [comment]
@WonderCsabo, could you merge the wiki for me ?

**Comment by WonderCsabo** [comment]
Done!

**Pull request merged**
