### PR TITLE
WIP Plugin system

### PR DESCRIPTION
**Pull request by yDelouis**
This PR is not ready at all and is created only to show the work in progress so that people can comment.

### CODE REVIEW

**Comment by yDelouis** [comment]
What would be the folder and maven structure ? I think you proposal will be strange for plugins because we will have : (in [], it is the maven module name)
````
- AndroidAnnotations [androidannotations-parent]
  | - core [??]
    | - androidannotations [androidannotations]
    | - androidannotations-api [androidannotations-api]
    | - androidannotations-test [androidannotations-test]
  | - ormlite [??]
    | - ormlite [ormlite]
    | - ormlite-api [ormlite-api]
    | - ormlite-test [ormlite-test]
````

**Comment by WonderCsabo** [comment]
What about this?

````
- AndroidAnnotations [androidannotations-parent]
  | - androidannotations-core [androidannotations-core]
    | - androidannotations [androidannotations]
    | - androidannotations-api [androidannotations-api]
    | - androidannotations-test [androidannotations-test]
  | - androidannotations-ormlite [androidannotations-ormlite]
    | - ormlite [ormlite]
    | - ormlite-api [ormlite-api]
    | - ormlite-test [ormlite-test]
````

**Comment by yDelouis** [comment]
Your proposition makes sense.
The only thing I don't like is that the names are very long and it won't fit on one line in my terminal.

**Comment by ened** [comment]
Do you guys have a mvn snapshot repo (maybe via github) for this PR, so interested folks could help testing?

**Comment by dodgex** [comment]
as far as i know no, but you can checkout https://github.com/yDelouis/androidannotations/tree/957_plugins and run `mvn install` to get the snapshot into your local mvn repo

**Comment by WonderCsabo** [comment]
@dodgex is right, we do not have a repo, but interested folks can really simple build the lib itself. I really hope this will be merged into develop soon, after that you can try in the conventional OSS snapshot repo.

**Comment by dodgex** [comment]
Nice! Finally merged. :D

**Comment by dodgex** [comment]
Let the Plugin Hell begin :smile:

**Pull request merged**
