### PR TITLE
Allow subclasses to override @OptionsItem handling

### PR DESCRIPTION
**Pull request by WonderCsabo**
Implements #1067.

@yDelouis i think this may be a breaking change, as clients could rely on the old behavior in their apps.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
@yDelouis do you agree?

**Comment by WonderCsabo** [comment]
OK, so it is not a breaking change then. :)

**Comment by yDelouis** [comment]
It's not mentioned in the doc. So we didn't changed the API but the internal implementation.
But we could move this to 4.0 if you think it's important.

**Comment by WonderCsabo** [comment]
This is OK.

**Pull request merged**
