### PR TITLE
Stop validation when injectHelper invalidated the annotation (#1795)

### PR DESCRIPTION
**Pull request by dodgex**
see https://github.com/excilys/androidannotations/issues/1795

### CODE REVIEW

**Comment by WonderCsabo** [comment]
Lots of CS violatons. 😄

**Comment by WonderCsabo** [comment]
Can you add a compile-time test case from the original issue?

**Comment by dodgex** [comment]
>.< :D

I grepped the if statement into the code and missed the spaces :/

**Comment by dodgex** [comment]
i'll merge the commits - just used a free minute (hopefully) fix the CS violations from web :D

**Comment by dodgex** [comment]
@WonderCsabo updated

**Pull request merged**
