### PR TITLE
Create blocks for injection and after injection

### PR DESCRIPTION
**Pull request by WonderCsabo**
Related to #1466.

This is incomplete. For some reasons, it generates the following:
```java
private void init_(Bundle savedInstanceState) {
	{
		Resources resources_ = this.getResources();
		injected_string = resources_.getString(R.string.injected_string);
		injectedString = resources_.getString(R.string.injected_string);
		helloHtml = Html.fromHtml(resources_.getString(R.string.hello_html));
		htmlInjected = Html.fromHtml(resources_.getString(R.string.hello_html));
	}
}
```

Note the extra block with braces and indent. I could not figure out why is this happening. Any help is much appreciated.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
The problem can be seen in `ContextCompatDrawableTest.activityCompilesOnMinSdkLower21CompileSdkHigher21WithoutContextCompat()`.

**Comment by dodgex** [comment]
i have a similar problem. jcodemodel sets the braces to required as soon as one calls `decl`. see [JBlock.java#L275](https://github.com/phax/jcodemodel/blob/master/src/main/java/com/helger/jcodemodel/JBlock.java#L275)

**Comment by WonderCsabo** [comment]
Thanks! I just realized this myself. See https://github.com/phax/jcodemodel/issues/32.

**Comment by dodgex** [comment]
haha :) good to know. btw we can do some kind of workaround by calling `.bracesRequired(false).indentRequired(false);` but this is... kind of ugly :(

**Comment by yDelouis** [comment]
Great.

**Pull request merged**
