### PR TITLE
fixes #1604

### LINKED ISSUE #1604: @ColorRes should use ContextCompat.getColor if available
Currently we use `Resources.getColor()`, but it was deprecated in API 23. The `ContextCompat.getColor()` method should be used instead, but only if it is available.

### PR DESCRIPTION
**Pull request by ened**
Use ContextCompat for color & ColorStateList resources.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
Great, thanks! Can you create a superclass and move all common methods up to it from `DrawableResHandler`, `ColorRestHandler` and `ColorStateListResHandler`?

**Comment by ened** [comment]
Yes how about *ContextCompatAwareResHandler* ?

**Comment by WonderCsabo** [comment]
Sounds good!

**Comment by WonderCsabo** [comment]
@ened is this ready to be reviewed?

**Comment by ened** [comment]
@WonderCsabo yes please.

**Comment by WonderCsabo** [comment]
Great work! Thanks.

**Pull request merged**
