### PR TITLE
Fix PreferenceActivity RuntimeException with @PreferenceScreen

### LINKED ISSUE #1392: RuntimeException with @PreferenceScreen
Hi,
I've tried to implement the preference screen in my app today and stumbled upon this bug (or am I doing something wrong?) 

I have created a xml file with preferences, and annotated the activity : 
``` java
@PreferenceScreen(R.xml.preferences)
@EActivity
public class SettingsActivity extends PreferenceActivity {
}
``` 
and it gives me the error:

```    
Caused by: java.lang.RuntimeException: This should be called after super.onCreate.
            at android.preference.PreferenceActivity.requirePreferenceManager(PreferenceActivity.java:1439)
            at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1511)
            at package.name.SettingsActivity_.init_(SettingsActivity_.java:38)
            at package.name.SettingsActivity_.onCreate(SettingsActivity_.java:32)
            at android.app.Activity.performCreate(Activity.java:5990)
```

I guess the problem is in the generated class:

``` java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState); // that line should be after onCreate (line 32)
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        addPreferencesFromResource(xml.preferences); // line 38
    }
``` 

Is there anyone who can confirm the bug or indicate my mistake (I did everything as in the wiki section, so I think all should be fine)
Cheers!

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #1392.

### CODE REVIEW

**Comment by dodgex** [comment]
assuming that you did a small test with a "real" app i'd say lgtm! ;)

**Comment by WonderCsabo** [comment]
Yeah, i did it with the example app.

**Comment by yDelouis** [comment]
I didn't test this myself but I trust you and the code seems OK.

**Comment by WonderCsabo** [comment]
Rebased and merged as of 571508b.

**Pull request closed without merging**
