### PR TITLE
Fix bug with calculation of serial remaining delay

### LINKED ISSUE #1685: @Background: BackgroundExecutor delay is calculated wrongly. Task is never called.
There seems to be a bug in `BackgroundExecutor` class. The `remainingDelay` of the next task (same serial) is set wrongly.

**To reproduce:**

```java
@EActivity
public class MainActivity extends AppCompatActivity {

    private static final String TAG = "APP";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        firstTaskNoDelay();
        secondTaskWithDelay();
    }

    @Background(serial = "serial1")
    void firstTaskNoDelay() {
        Log.d(TAG, "Executing task 1");
        try {
            Thread.sleep(6000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Background(serial = "serial1", delay = 1000)
    void secondTaskWithDelay() {
        Log.d(TAG, "Executing task 2"); // <-- this is not called (delayed by a huge time)
    }
}
```

There are two tasks with same serial. First one with no delay, second one with delay 1000. The calculation of `next.remainingDelay` is incorrect which causes the second task to be delayed by a huge time.

**Buggy method:**
There is issue when casting long to int.
```java
private void postExecute() {
	if (id == null && serial == null) {
		/* nothing to do */
		return;
	}
	CURRENT_SERIAL.set(null);
	synchronized (BackgroundExecutor.class) {
		/* execution complete */
		TASKS.remove(this);

		if (serial != null) {
			Task next = take(serial);
			if (next != null) {
				if (next.remainingDelay != 0) {
					/* the delay may not have elapsed yet */
					// =============  BUG HERE  ============= 
					next.remainingDelay = Math.max(0, (int) (targetTimeMillis - System.currentTimeMillis()));
					/* 
					 * targetTimeMillis => 0 
				     * System.currentTimeMillis() => 1453870701164l
				     * (int) (targetTimeMillis - System.currentTimeMillis()) => ((int) (0 - 1453870701164l)) => 2123212180
				     * next.remainingDelay =>  2123212180  <-- WRONG
				     */
				}
				/* a task having the same serial was queued, execute it */
				BackgroundExecutor.execute(next);
			}
		}
	}
}
```

**Proposed Fix:**
```java
next.remainingDelay = Math.max(0l, targetTimeMillis - System.currentTimeMillis());
```

**Update**:
Interestingly this bug will start to happen for all users from today (Tue Jan 26 2016 22:13:49 UTC time) onwards as the `System.currentTimeMillis()` value exceeds `1453846429696l`. 
```
(int)(0 - 1453846429696l) = -2147483648 // <-- negative (so no bug)
(int)(0 - 1453846429697l) = 2147483647  // <-- positive (bug starts to happen)
```

Let me know if I have misunderstood anything.

Regards
-Amulya

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #1685.

### CODE REVIEW

**Comment by yDelouis** [comment]
Code is okay IMHO.

**Comment by dodgex** [comment]
maybe use long for all delay related places to be consistent? ( e.g. [BackgroundExecutor.java#L383](https://github.com/WonderCsabo/androidannotations/blob/1685_serialDelayBug/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java#L383) and possibly the annotation itself?)

otherwise it looks okay for me too. :)

**Comment by WonderCsabo** [comment]
@dodgex good point, i also thought about that.

**Comment by WonderCsabo** [comment]
@dodgex updated.

**Comment by dodgex** [comment]
you missed the [handler](https://github.com/excilys/androidannotations/blob/4e2bccfca60d3875dd22d157f5ff88e84a2dfe8a/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/BackgroundHandler.java#L73)

**Comment by WonderCsabo** [comment]
Yep, you are right. :( Updated again.

**Comment by dodgex** [comment]
i think i should be okay now. good work :+1:

**Comment by dodgex** [comment]
@WonderCsabo @yDelouis i think this is something that we should hotfix for 3.x too. as @amulyakhare has pointed out that this issue is affecting all apps that use this combination and 4.0 is a beaking change so there is no drop-in update possible (at least not recommendable).

**Pull request merged**
