### PR TITLE
Fix generic issues

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes generic issues raised in #1402 and #1403.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
I also generified the return type of Fragment arg builder methods.

**Comment by yDelouis** [comment]
The generated class of `GenericClient` is : 
```java
public final class GenericClient_<T extends Object >
    implements GenericClient
{

    private String rootUrl;
    private RestTemplate restTemplate;

    public GenericClient_(Context context) {
        rootUrl = "";
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().clear();
        restTemplate.getMessageConverters().add(new StringHttpMessageConverter());
    }
}
````
I think it should implement `GenericClient<T>` instead of `GenericClient`.

**Comment by WonderCsabo** [comment]
@yDelouis you are right.

**Comment by WonderCsabo** [comment]
Fixed and rebased to develop.

**Comment by WonderCsabo** [comment]
@yDelouis can we merge this?

**Comment by yDelouis** [comment]
Is there some generic fragment, view and bean to see your changes ?

**Comment by WonderCsabo** [comment]
`SomeGenericViewGroup` in the compile time test. There is no generic `Fragment` in the code base, i guess i should add one in the compile time test.

**Comment by WonderCsabo** [comment]
There is a generic `Fragment` in #1445, so i do not want to add it here. Please copy it for your test.

**Pull request merged**
