### PR TITLE
Better generated source encoding support

### PR DESCRIPTION
**Pull request by WonderCsabo**
The default encoding is now UTF-8, and the encoding can be configured with the `encoding` annotation processing option.

Implements #1746 .

### CODE REVIEW

**Comment by dodgex** [comment]
don't we need to add the new option [here](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/Options.java#L40)?

**Comment by WonderCsabo** [comment]
You are right!

**Comment by WonderCsabo** [comment]
@dodgex updated.

**Comment by dodgex** [comment]
I think it looks good now. :)

**Pull request merged**
