### PR TITLE
ValidatorParameterHelper fluent API

### PR DESCRIPTION
**Pull request by WonderCsabo**
Implements #1284.

This is only a WIP, but i am sharing the work, to get an early response about the direction, @yDelouis @dodgex.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
@yDelouis i implemented all of your proposals, expect the annotation checking (too specific case, and the classes are already too complicated). Please check out!

**Comment by WonderCsabo** [comment]
For future reference see relevant discussion in https://github.com/WonderCsabo/androidannotations/pull/2.

**Comment by WonderCsabo** [comment]
FInally this is merged. Thanks @yDelouis for your great work on this one!

**Comment by dodgex** [comment]
First of all: nice work @WonderCsabo and @yDelouis :)

from what i have seen, there is no javadoc on these new api? I think it would be nice to have some kind of documentation how this works. especially as soon as we have a plugin system lots of internals (everything that is a public api for plugins) needs to be well documented.

**Comment by WonderCsabo** [comment]
Actually i thought we should add JavaDoc for the most important API-s used by plugins. We should include this one as well.
Also, we may have to move all classes which are not available for plugins to an internal package.

**Comment by yDelouis** [comment]
I agree, and we should discuss it on the issue #957.

**Comment by WonderCsabo** [comment]
:+1: I just see i already mentioned the JavaDoc there. :)

**Pull request merged**
