### PR TITLE
Fix for Parcelable[] ClassCastException

### LINKED ISSUE #1208: ClassCastException when using @Extra with Parcelable[] objects
Given I have a model class `RemoteMediaFile`, which is roughly defined like this:
``` java
public class RemoteMediaFile implements Parcelable {
    private String mId;
    private String mParentId;
    public RemoteMediaFile() {
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.mId);
        dest.writeString(this.mParentId);
    }

    private RemoteMediaFile(Parcel in) {
        this.mId = in.readString();
        this.mParentId = in.readString();
    }

    public static final Creator<RemoteMediaFile> CREATOR = new Creator<RemoteMediaFile>() {
        public RemoteMediaFile createFromParcel(Parcel source) {
            return new RemoteMediaFile(source);
        }

        public RemoteMediaFile[] newArray(int size) {
            return new RemoteMediaFile[size];
        }
    };
}
```

Then I'd like to use `@Extra` in my `Activity`, which should read the array from an Intent:

``` java
@EActivity
public class RemotePhotoDetailActivity extends BaseActivity implements RemotePlayer{
    @Extra
    protected RemoteMediaFile[] remoteFiles;
}
```

However, this creates a ClassCastException:

```
Caused by: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to com.myapp.media.RemoteMediaFile[]
       at com.myapp.photos.RemotePhotoDetailActivity_.injectExtras_(RemotePhotoDetailActivity_.java:168)
       at com.myapp.photos.RemotePhotoDetailActivity_.init_(RemotePhotoDetailActivity_.java:109)
       at com.myapp.photos.RemotePhotoDetailActivity_.onCreate(RemotePhotoDetailActivity_.java:103)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
       at android.app.ActivityThread.access$800(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(Native Method)
```

The generated code looks like this:

``` java
    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(REMOTE_FILES_EXTRA)) {
                remoteFiles = ((RemoteMediaFile[]) extras_.getParcelableArray(REMOTE_FILES_EXTRA));
            }
        }
    }
```

A fix would be to read the `RemoteMediaFile[]` object from the intent like this:

``` java
    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(REMOTE_FILES_EXTRA)) {
                Parcelable[] a = extras_.getParcelableArrayExtra(REMOTE_FILES_EXTRA);
                remoteFiles = Arrays.copyOf(a, a.length, RemoteMediaFile[].class);
            }
        }
    }
```

When I do this manually, it will work properly.

More details here: http://stackoverflow.com/a/10781119/375209

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #1208.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
@yDelouis please review this PR.

**Comment by yDelouis** [comment]
Could you take into account my comment and add a test ?

**Comment by WonderCsabo** [comment]
9cc165e modifies the already existing test so it will behave like the Android code.

**Comment by yDelouis** [comment]
Ok, but I didn't see any test where a `Parcelable` array is put in a bundle and restored from it.

**Comment by WonderCsabo** [comment]
https://github.com/WonderCsabo/androidannotations/blob/9cc165ece5fadb295a05ffdbed6ac63a62e4724f/AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/instancestate/SaveInstanceStateActivityParameterizedTest.java#L89

**Comment by yDelouis** [comment]
Sorry, I looked too quickly.

**Comment by WonderCsabo** [comment]
@yDelouis i addressed your comment. I also moved 69002c5 to #1352, because that commit no longer needed for this fix, but it is still a good refactor.

**Comment by yDelouis** [comment]
Good work. Thanks.

**Pull request merged**
