### PR TITLE
do not call setIntent() in onNewIntent()

### PR DESCRIPTION
**Pull request by dodgex**
see https://github.com/excilys/androidannotations/issues/1578

### CODE REVIEW

**Comment by WonderCsabo** [comment]
Hmm, we did not have tests for this?

BTW, you are *fast*.

**Comment by dodgex** [comment]
does not seem to be tested. there where no failures

**Comment by dodgex** [comment]
i flash! =)

**Comment by WonderCsabo** [comment]
@dodgex can you update the wiki and add a warning about this breaking change?

**Comment by dodgex** [comment]
hmmm looks like we never mentioned that we override onNewIntent. do you know with which version we introduced the override?

**Comment by WonderCsabo** [comment]
AA 3.2.

**Comment by dodgex** [comment]
https://github.com/dodgex/androidannotations/wiki/Extras#handling-onnewintent

**Comment by dodgex** [comment]
Thank you for the info. :)

**Comment by WonderCsabo** [comment]
Wiki merged, thx.

**Pull request merged**
